using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Transport_Management_System.Models
{
    public class Shipment
    {
        [Key]
        public int ShipmentId { get; set; }

        // Auto-generated by the controller — NOT submitted by the user
        [Display(Name = "Shipment Reference")]
        [StringLength(50)]
        public string ShipmentRef { get; set; } = string.Empty;

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        [StringLength(300)]
        public string Description { get; set; } = string.Empty;

        [Required(ErrorMessage = "Sender Name is required")]
        [Display(Name = "Sender Name")]
        [StringLength(100)]
        public string SenderName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Sender Contact is required")]
        [Display(Name = "Sender Contact")]
        [StringLength(50)]
        public string SenderContact { get; set; } = string.Empty;

        [Required(ErrorMessage = "Receiver Name is required")]
        [Display(Name = "Receiver Name")]
        [StringLength(100)]
        public string ReceiverName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Receiver Contact is required")]
        [Display(Name = "Receiver Contact")]
        [StringLength(50)]
        public string ReceiverContact { get; set; } = string.Empty;

        [Required(ErrorMessage = "Origin is required")]
        [StringLength(200)]
        public string Origin { get; set; } = string.Empty;

        [Required(ErrorMessage = "Destination is required")]
        [StringLength(200)]
        public string Destination { get; set; } = string.Empty;

        [Display(Name = "Weight (kg)")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Weight must be greater than 0")]
        public double WeightKg { get; set; }

        [Display(Name = "Shipment Type")]
        public ShipmentType ShipmentType { get; set; }

        [Display(Name = "Status")]
        public ShipmentStatus Status { get; set; } = ShipmentStatus.Pending;

        // Optional Vehicle assignment
        [Display(Name = "Assigned Vehicle")]
        public int? VehicleId { get; set; }

        [ForeignKey("VehicleId")]
        public Vehicle? Vehicle { get; set; }

        [Display(Name = "Dispatch Date")]
        [DataType(DataType.Date)]
        public DateTime? DispatchDate { get; set; }

        [Display(Name = "Expected Delivery")]
        [DataType(DataType.Date)]
        public DateTime? ExpectedDelivery { get; set; }

        [Display(Name = "Actual Delivery")]
        [DataType(DataType.Date)]
        public DateTime? ActualDelivery { get; set; }

        [Display(Name = "Freight Charge (BDT)")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal FreightCharge { get; set; } = 0;

        [StringLength(500)]
        public string? Notes { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}
